# Generated by Django 2.1.3 on 2018-11-29 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnysociety.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('startDate', models.TimeField()),
                ('endDate', models.TimeField()),
                ('venue', models.CharField(max_length=500)),
                ('timestamp', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('isPendingRequest', models.BooleanField()),
                ('isReceivedRequest', models.BooleanField()),
                ('party1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_party', to=settings.AUTH_USER_MODEL)),
                ('party2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_party', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('timestamp', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnysociety.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_party', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnysociety.SiteUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnysociety.SiteUser'),
        ),
    ]
